Homework 7
websafarispb/EvgeniiStepanov pull request #8
Opened 2021-07-05 17:06 UTC by websafarispb

2021-07-13 21:30 UTC, pnatashap requested changes
Два замечания: по тесту - слишком сложно понять, что происходит. и нужно сделать, чтобы работало при любом количестве данных в json файле.

2021-07-13 21:30 UTC, pnatashap commented on src/test/java/ru/stepev/test/training/at/hw7/utils/PropertyReader.java
> +        InputStream is = PageDataProvider.class.getResourceAsStream("/pages.properties");
классно, что читаешь ресурс!

2021-07-13 21:30 UTC, pnatashap commented on src/test/resources/pages.properties
> +json.win.file=src\\test\\resources\\JDI_ex8_metalsColorsDataSet.json
вот тут бы тоже аналог ресурса было бы отлично:
если хотчется скомпилировать один раз, а выполнять несколько раз, то файл всегда оказывается снаружи. 
(просто на будущее, не надо исправлять)

2021-07-13 21:30 UTC, pnatashap commented on src/test/java/ru/stepev/test/training/at/hw7/test/SiteJdiTest.java
> +        homePage.open();
правило: тест должен влезать в экран, выполнено, но выглядит как-то очень сложно.
давай чуток подшлифуем, чтобы было красиво: 2отдельно выделим операции, которые могут пригодится не только тут: например логин, разлогин. и дальше заполнение, чтобы было понятнее, что собственно происходит.

2021-07-13 21:30 UTC, pnatashap commented on src/test/java/ru/stepev/test/training/at/hw7/dataprovider/PageDataProvider.java
> +                 .password(pageProperty.getProperty("Page.userPassword")).build(), jsonDate.get("data_1")},
был уговор, что количество строк в файле может меняться. может быть две только, может стать 10.

2021-07-14 12:28 UTC, websafarispb commented on src/test/java/ru/stepev/test/training/at/hw7/test/SiteJdiTest.java
> +        homePage.open();
исправил

2021-07-14 12:28 UTC, websafarispb commented on src/test/java/ru/stepev/test/training/at/hw7/dataprovider/PageDataProvider.java
> +                 .password(pageProperty.getProperty("Page.userPassword")).build(), jsonDate.get("data_1")},
исправил

2021-07-14 12:29 UTC, websafarispb commented on src/test/java/ru/stepev/test/training/at/hw7/utils/PropertyReader.java
> +        InputStream is = PageDataProvider.class.getResourceAsStream("/pages.properties");
спасибо :)

2021-07-14 21:44 UTC, pnatashap approved these changes
гораздо лучше

2021-07-14 21:44 UTC, pnatashap commented on src/test/java/ru/stepev/test/training/at/hw7/model/pages/MetalAndColor.java
> +    public void logOut() {
странно выглядит, что логинимся на одной странице, а logout на другой. :)

2021-07-15 18:01 UTC, merged